apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-hello-world
  generateName: deploy-hello-world-
spec:
  pipelineRef:
    name: deploy-java-app
  workspaces:
    - name: git-repo
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Mi
            