kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: pv0009
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: 200Mi
