apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-run-
spec:
  pipelineRef:
    name: clone-build
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials 
  params:
  - name: repo-url
    value: https://github.com/google/docsy-example.git
  - name: image-reference
    value: docker.io/emeafez/docsy-example:latest
  - name: dockerfile
    value: ./Dockerfile
  # - name: extra-args
  #   value: [--no-push]
  - name: builder-image
    value: gcr.io/kaniko-project/executor:v1.9.0-debug