apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: output-pipeline
spec:
  params:
    - name: greeting
      type: string
  workspaces:
    - name: output-workspace
  tasks:
    - name: output-task
      taskRef:
        name: output-task
      workspaces:
        - name: messages
          workspace: output-workspace
      params:
        - name: greeting
          value: $(params.greeting)
    - name: input-task
      taskRef:
        name: input-task
      workspaces:
      - name: messages
        workspace: output-workspace
      runAfter:
        - output-task

