apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: greeting-deployment
  annotations:
    tekton.dev/pipelines.minVersion: "1.0"
spec:
  params:
    - name: image-url
      type: string
    - name: image-tag
      type: string
      default: latest
  steps:
    - name: create-new-app
      image: registry.redhat.io/openshift3/ose-cli@sha256:04e40e6669a472250301260034e96d2bd4dace5679686433c551744898b29801
      env:
        - name: IMAGE
          value: $(params.image-url):$(params.image-tag)
      command: ["oc"]
      args:
      - create
      - new-app
      - $IMAGE
      - --name=greeting-tekton
      - -l 'app=greeting-tekton' 
    - name: create-route
      command: ["oc"]
      image: registry.redhat.io/openshift3/ose-cli@sha256:04e40e6669a472250301260034e96d2bd4dace5679686433c551744898b29801
      args:
      - create
      - route
      - edge
      - greeting-tekton
      - --service=greeting-tekton
      
