apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-java-app
  labels:
    app.kubernetes.io/version: "1.0"
spec:
  workspaces:
    - name: git-repo
  params:
    - name: git-url
      type: string
      default: https://github.com/BuntyRaghani/spring-boot-hello-world
    - name: image-path
      type: string
      default: image-registry.openshift-image-registry.svc:5000/<namespace>/
    - name: app-name
      type: string
      default: hello-world
    - name: image-tag
      type: string
      default: latest
  tasks:
    - name: clone-java-app
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: output
          workspace: git-repo
    - name: s2i-java
      taskRef:
        kind: ClusterTask
        name: s2i-java
      runAfter: 
        - clone-java-app
      params:
        - name: IMAGE
          value: $(params.image-path)$(params.app-name)
        - name: VERSION
          value: latest
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: git-repo
    - name: oc-delete-old-app
      taskRef:
        kind: ClusterTask
        name: openshift-client
      runAfter:
        - s2i-java
      params:
        - name: SCRIPT
          value: |
            #!/bin/sh
            oc delete all -l 'app=$(params.app-name)'
    - name: oc-deployment
      taskRef:
        kind: ClusterTask
        name: openshift-client
      runAfter:
        - oc-delete-old-app
      params:
        - name: SCRIPT
          value: |
            #!/bin/sh
            oc new-app $(params.image-path)$(params.app-name):$(params.image-tag) -l 'app=$(params.app-name)'
    - name: oc-create-route
      taskRef:
        kind: ClusterTask
        name: openshift-client
      runAfter:
        - oc-deployment
      params:
        - name: SCRIPT
          value: |
            #!/bin/sh
            oc create route edge $(params.app-name) --service=$(params.app-name)
 