apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: greeting-pipeline
  labels:
    app.kubernetes.io/version: "1.0"
spec:
  workspaces:
    - name: git-repo
  params:
    - name: git-url
      type: string
      default: https://github.com/redhat-scholars/tekton-tutorial-greeter
    - name: image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/dev-tekton/greeting-tekton
    - name: image-tag
      type: string
      default: latest
  tasks:
    - name: clone-greeting-repo
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: output
          workspace: git-repo
    - name: s2i-java
      taskRef:
        kind: ClusterTask
        name: s2i-java
      runAfter: 
        - clone-greeting-repo
      params:
        - name: IMAGE
          value: $(params.image)
      workspaces:
        - name: source
          workspace: git-repo
    - name: greeting-deployment
      taskRef:
        name: greeting-deployment
      runAfter:
        - s2i-java
      params:
        - name: image-url
          value: $(params.image)
        - name: image-tag
          value: $(params.image-tag)

