apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    name: cluster-task-pipeline
    namespace: default
spec:
    params:
        - name: message
          type: string
    workspaces:
        - name: from-beyond
    tasks:
        - name: cluster-resolver-task
          taskRef:
              name: cluster-resolver-task
              kind: Task
          params:
            - name: message
              value: $(params.message)
          workspaces:
            - name: tektonic
              workspace: from-beyond
        - name: cluster-task
          taskRef:
              name: cluster-task
              kind: ClusterTask
          params:
            - name: message
              value: $(params.message)
          workspaces:
            - name: tektonic
              workspace: from-beyond


