apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cluster-pipeline
spec:
  workspaces:
    - name: obetsun-dev-shared
    - name: maven-settings
  params:
    - name: git-url
      type: string
    - name: gitRevision
      type: string
      description: The git branch to clone.
    - name: contextDir
      description: the context directory from where to build the application
      default: .
    - name: baseImage
      description: base image to run maven build and output image build
      default: registry.access.redhat.com/ubi8/openjdk-11
    - name: mavenRepoVolume
      description: Volume name for maven local repo volume
      default: mvn-repo-empty
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: obetsun-dev-shared
      params:
        - name: url
          value: $(params.git-url)
    - name: compile
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
        - clone-repo
      params:
        - name: MAVEN_IMAGE
          value: $(params.baseImage)
        - name: CONTEXT_DIR
          value: $(params.contextDir)
        - name: GOALS
          value:
            - clean
            - compile
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: obetsun-dev-shared
